# Site settings
title: CTT
email: pedro@pjrt.co
description: > # this means to ignore newlines until "baseurl:"
    Everyone else seems to have a blog
github_username:  pjrt
twitter:
    username: _pjrt

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap
    - jekyll-seo-tag
