# Site settings
title: Can't Think of a Title
email: pedro@pjrt.co
description: > # this means to ignore newlines until "baseurl:"
    Everyone else seems to have a cool github.io site, so why not?
github_username:  pjrt

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap
